def PatternCount(a,b):
    kmers = []
    counter = 0
    for i in range(len(a) - (len(b) - 1)):
        kmers.append(a[i:i+ len(b)])
    for j in range(0, len(a)):
        if(str(a[j:j+len(b)]) == str(b)):
          counter += 1
    print(counter)
PatternCount("GCTACCGAGTTTCCGACTACCGACTACCGACTGCTACCGATATCTACCGACCCTACCGAGGCTCCTACCGATACCTACCGAGTTCGAAGTTCTACCGATCTACCGATCTGCTACCGACTACCGATTTCTACCGACTACCGACTACCGAAGATTCTACCGATCTACCGATGCTACCGACTACCGACCTACCGAATCTACCGACTACCGACTACCGACTACCGACGCTACCGAGCGGGTTCTACCGACTACCGAGAAGCTACCGACCTAACTACCGACGACTACCGAGACGCTACCGAAAGCCCTACCGACTACCGAAACTACCGACTACCGATCTACCGACTACCGACTACCGACGGACTGGGCTACCGACTACCGAGCTACCGATCATCTCCCCCTACCGAGAACCTACCGACCTACCGAAACTACCGATTCTACCGACTACCGAATACTACCGACTACCGACTACCGATCACTACCGAAGCTACCGACTCTACCGAGGCTACCGACTCTACCGAGGCTCTACCGAAGACTACCGACTAGCCGCCTACCGAACCTACCGACTACCGACTACCGAAGTCTACCGAGCCTACCGATCTACCGAGTTGAGCCTACCGAAACGTCTACCGATTCTACCGATTCCTACCGACCCTACCGATCTACCGATGCTACCGAGGAGACCTACCGAGGCTACCGACTACCGATGAGACTACCGACTACCGACTGACTACCGACTACCGACATAACTACCGACCTACCGACTACCGAGACTACCGACTACCGACTACCGACTACCGACTACCGAACTACCGACTACCGAGGCTACCGACCTACCGACTACCGACTACCGACATTACCTACCGAAGCTACCGACTACCGACCGTCGCGCAGAGAAGTCTACCGAGAGCGCTACCGAGATCTACCGAGCTACCGACTACCGAGGCCTACCGAGACTACCGAATTGTCAATCTACCGAGGTCTACCGATCTACCGAGGACTACCGAA", "CTACCGACT")

